export const  VehicleData = [
    {
      id:1,
      icon: 'fa fa-solid fa-truck',
      vehicleId: 'ET-272-KJA',
      vehicleInfo: 'Toyota Highlander 2004',
      location: 'Lagos',
      locationDescription: 'Start Location',
      sLocation: "Ikeja",
      sLocationD: "Destination",
      info: 'In Transit',
      infoInfo: "Status",
      driverName: 'Johnson C',
      circle:"fa fa-solid fa-circle",
  },
  {
    id:2,
    icon: 'fa fa-solid fa-truck',
    vehicleId: 'ET-272-KJA',
    vehicleInfo: 'Toyota Highlander 2004',
    location: 'Lagos',
    locationDescription: 'Start Location',
    sLocation: "Ikeja",
    sLocationD: "Destination",
    info: 'In Transit',
    infoInfo: "Status",
    driverName:'Jeremy Lopez',
    circle:"fa fa-solid fa-circle span-two",
},{
    id:3,
    icon: 'fa fa-solid fa-truck',
    vehicleId: 'ET-272-KJA',
    vehicleInfo: 'Toyota Highlander 2004',
    location: 'Lagos',
    locationDescription: 'Start Location',
    sLocation: "Ikeja",
    sLocationD: "Destination",
    info: 'In Transit',
    infoInfo: "Status",
    driverName:'Indiana Jones',
    circle:"fa fa-solid fa-circle span-three",
},
{
    id:4,
    icon: 'fa fa-solid fa-truck',
    vehicleId: 'ET-272-KJA',
    vehicleInfo: 'Toyota Highlander 2004',
    location: 'Lagos',
    locationDescription: 'Start Location',
    sLocation: "Ikeja",
    sLocationD: "Destination",
    info: 'In Transit',
    infoInfo: "Status",
    driverName:'Jeremy Lopez',
    circle:"fa fa-solid fa-circle span-four",
},
{
    id:5,
    truck:'fa fa-solid fa-truck-front',
    icon: 'fa fa-solid fa-truck-pickup',
    vehicleId: 'ET-272-KJA',
    vehicleInfo: 'Toyota Hillux 2004',
    location: 'Lagos',
    locationDescription: 'Start Location',
    sLocation: "Ikeja",
    sLocationD: "Destination",
    info: 'In Transit',
    infoInfo: "Status",
    driverName:'Jeremy Lopez',
    circle:"fa fa-solid fa-circle",
},
{
    id:6,
    truck:'fa fa-solid fa-truck-front',
    icon: 'fa fa-solid fa-truck-pickup',
    vehicleId: 'ET-272-KJA',
    vehicleInfo: 'Toyota Hillux 2004',
    location: 'Lagos',
    locationDescription: 'Start Location',
    sLocation: "Ikeja",
    sLocationD: "Destination",
    info: 'In Transit',
    infoInfo: "Status",
    driverName:'Jeremy Lopez',
    circle:"fa fa-solid fa-circle span-two",
},
{
    id:7,
    truck:'fa fa-solid fa-truck-front',
    icon: 'fa fa-solid fa-truck-pickup',
    vehicleId: 'ET-272-KJA',
    vehicleInfo: 'Toyota Hillux 2004',
    location: 'Lagos',
    locationDescription: 'Start Location',
    sLocation: "Ikeja",
    sLocationD: "Destination",
    info: 'In Transit',
    infoInfo: "Status",
    driverName:'Jeremy Lopez',
    circle:"fa fa-solid fa-circle span-three",
},
{
    id:8,
    trailers:'fa fa-solid fa-truck-front',
    icon: 'fa fa-solid fa-caravan',
    vehicleId: 'ET-272-KJA',
    vehicleInfo: 'Trailer Highlander 2004',
    location: 'Lagos',
    locationDescription: 'Start Location',
    sLocation: "Ikeja",
    sLocationD: "Destination",
    info: 'In Transit',
    infoInfo: "Status",
    driverName:'Jeremy Lopez',
    circle:"fa fa-solid fa-circle span-two",
},
{
    id:9,
    trailers:'fa fa-solid fa-truck-front',
    icon: 'fa fa-solid fa-caravan',
    vehicleId: 'ET-272-KJA',
    vehicleInfo: 'Trailer Highlander 2004',
    location: 'Lagos',
    locationDescription: 'Start Location',
    sLocation: "Ikeja",
    sLocationD: "Destination",
    info: 'In Transit',
    infoInfo: "Status",
    driverName:'Jeremy Lopez',
    circle:"fa fa-solid fa-circle",
},
{
    id:10,
    tankers:'fa fa-solid fa-truck-front',
    icon: 'fa fa-solid fa-truck-bolt',
    vehicleId: 'ET-272-KJA',
    vehicleInfo: 'Fuel Tanker 2004',
    location: 'Lagos',
    locationDescription: 'Start Location',
    sLocation: "Ikeja",
    sLocationD: "Destination",
    info: 'In Transit',
    infoInfo: "Status",
    driverName:'Jeremy Lopez',
    circle:"fa fa-solid fa-circle span-two",
},
{
    id:11,
    tankers:'fa fa-solid fa-truck-front',
    icon: 'fa fa-solid fa-truck-bolt',
    vehicleId: 'ET-272-KJA',
    vehicleInfo: 'Fuel Tanker 2004',
    location: 'Lagos',
    locationDescription: 'Start Location',
    sLocation: "Ikeja",
    sLocationD: "Destination",
    info: 'In Transit',
    infoInfo: "Status",
    driverName:'Jeremy Lopez',
    circle:"fa fa-solid fa-circle span-three",
},
{
    id:12,
    tankers:'fa fa-solid fa-truck-front',
    icon: 'fa fa-solid fa-truck-bolt',
    vehicleId: 'ET-272-KJA',
    vehicleInfo: 'Fuel Tanker 2004',
    location: 'Lagos',
    locationDescription: 'Start Location',
    sLocation: "Ikeja",
    sLocationD: "Destination",
    info: 'In Transit',
    infoInfo: "Status",
    driverName:'Jeremy Lopez',
    circle:"fa fa-solid fa-circle span-four",
},] 
